"""Scrutiny defense document generator."""
from __future__ import annotations

from models.session import AnalysisSession
from .generator import format_inr, get_financial_year


def generate_scrutiny_defense(session: AnalysisSession) -> dict:
    """Generate scrutiny defense document data."""
    metrics = session.compliance_result.metrics
    fy = get_financial_year()

    return {
        "title": f"Compliance Defense Report - {fy}",
        "prepared_for": "Income Tax Assessment / MSME Compliance Scrutiny",
        "sections": [
            {
                "heading": "1. Executive Summary",
                "content": (
                    f"This report documents compliance analysis of {metrics.total_invoices} invoices "
                    f"across {metrics.total_vendors} vendors ({metrics.msme_vendors} MSME). "
                    f"Overall compliance score: {metrics.compliance_score}/100."
                ),
            },
            {
                "heading": "2. MSMED Act 2006 Compliance",
                "content": (
                    f"MSME vendor analysis: {metrics.overdue_invoices} invoices overdue. "
                    f"Total overdue: {format_inr(metrics.total_overdue_amount)}. "
                    f"Interest liability identified: {format_inr(metrics.total_interest_liability)}. "
                    f"Interest has been computed at 3x RBI bank rate (19.5% p.a.) compounded monthly per Section 16."
                ),
            },
            {
                "heading": "3. Section 43B(h) Impact Assessment",
                "content": (
                    f"Potential tax disallowance: {format_inr(metrics.total_tax_disallowance)}. "
                    f"Payment plan initiated to clear overdue amounts before ITR filing deadline to preserve deductions."
                ),
            },
            {
                "heading": "4. MSME-1 Filing Status",
                "content": (
                    f"{metrics.msme1_filings_required} vendors require MSME-1 filing disclosure. "
                    "Half-yearly returns being prepared with complete vendor-wise breakdowns."
                ),
            },
            {
                "heading": "5. Remediation Actions",
                "content": (
                    f"Action plan generated with {len(session.action_plan.actions) if session.action_plan else 0} items. "
                    "Priority payments scheduled, interest provisions created, and MSME-1 filings initiated."
                ),
            },
            {
                "heading": "6. Audit Trail",
                "content": (
                    "Complete decision log maintained for all compliance calculations. "
                    "Each interest computation, risk score, and action decision is fully traceable."
                ),
            },
        ],
        "disclaimer": (
            "This document is auto-generated by LAWTRIX compliance engine. "
            "Contents should be verified by legal counsel before submission."
        ),
    }
